Update machine_learning stack extensions
tembo-io/tembo pull request #1098
Opened 2024-12-20 23:29 UTC by theory

Necessary to support Postgres 17, though it cannot be used until postgresml is updated.

2024-12-20 23:32 UTC, nhudson approved these changes

2024-12-20 23:54 UTC, ChuckHend requested changes
I'm almost certain pgml > 2.7.1 has new dependencies that are not in our ml image.

2024-12-21 00:09 UTC, theory commented
> I'm almost certain pgml > 2.7.1 has new dependencies that are not in our ml image.

It doesn't look like you changed anything in tembo-io/trunk@acc2c75, @ChuckHend.

2024-12-21 00:12 UTC, ChuckHend commented
> It doesn't look like you changed anything

I am referring to image that we use to run pgml on tembo-cloud. this PR will not run there.

2024-12-21 00:19 UTC, theory commented
> I am referring to image that we use to run pgml on tembo-cloud. this PR will not run there.

Ah, I assumed that since you didn't need to update dependencies to build it, then none would need to be updated in the image. I'll make a PR for the image.

2024-12-21 00:25 UTC, ChuckHend commented
I think it would be better to build pgml into the image rather than installing it from trunk. You'll be able to build the image and test it in dev before PRing here for the new image. Then this PR can be closed.

2024-12-21 00:43 UTC, theory commented
How does /tembo-io/tembo-images#77 look?

2025-01-13 20:32 UTC, closed without merging

2025-01-13 20:32 UTC, theory commented
Closing at we're deprecating this stack.