`conductor`: Add support for Azure Backup and Restore
tembo-io/tembo pull request #980
Opened 2024-09-26 11:18 UTC by ianstanton

2024-10-17 19:33 UTC, ianstanton commented on conductor/src/lib.rs
> +    info!("Created UAMI: {:?}", uami);
These are here for testing. I'll update with more appropriate logs.

2024-10-18 21:37 UTC, nhudson requested changes
Might be good to add a check like these to make sure you can't set aws or gcp also at the same time.  Other than that LGTM!  Great work!

```
    // Error and exit if both IS_CLOUD_FORMATION and IS_GCP are set to true
    if is_cloud_formation && is_gcp {
        panic!("Cannot have both IS_CLOUD_FORMATION and IS_GCP set to true");
    }

    // Error and exit if IS_GCP is true and GCP_PROJECT_ID or GCP_PROJECT_NUMBER are not set
    if is_gcp && (gcp_project_id.is_empty() || gcp_project_number.is_empty()) {
        panic!("GCP_PROJECT_ID and GCP_PROJECT_NUMBER must be set if IS_GCP is true");
    }
```

2024-10-18 23:09 UTC, ianstanton commented
> Might be good to add a check like these to make sure you can't set aws or gcp also at the same time. Other than that LGTM! Great work!
> 
> ```
>     // Error and exit if both IS_CLOUD_FORMATION and IS_GCP are set to true
>     if is_cloud_formation && is_gcp {
>         panic!("Cannot have both IS_CLOUD_FORMATION and IS_GCP set to true");
>     }
> 
>     // Error and exit if IS_GCP is true and GCP_PROJECT_ID or GCP_PROJECT_NUMBER are not set
>     if is_gcp && (gcp_project_id.is_empty() || gcp_project_number.is_empty()) {
>         panic!("GCP_PROJECT_ID and GCP_PROJECT_NUMBER must be set if IS_GCP is true");
>     }
> ```

Thanks, good suggestion! Addressed here https://github.com/tembo-io/tembo/pull/980/commits/a4b9cd5ef84393c7a6ba4a43f764afad8a0e1d08

2024-10-18 23:16 UTC, nhudson approved these changes

2024-10-21 20:42 UTC, merged